### ISSUE TITLE
Timezone resolution all of a sudden wrong

### ISSUE THREAD

**Issue by XXChester** [panthomakos/timezone#102]
Hello, earlier this week without a code change, our timezone resolution with this gem started returning the wrong zone.

My location is roughly here
```
latitude: 43.4733376
longitude: -80.5325744
```
Which should (and was) returning America/Toronto but now all of a sudden it is resolving to Europe/Moscow.

I've tried upgrading the gem to the latest version but it has the same problem. What changed? What did I miss?

Thanks.

**Comment by AlexWayfer** [comment]
What provider are you using?

```ruby
pry: main > gem-install timezone
Fetching timezone-1.3.6.gem
Gem `timezone` installed.
pry: main > Timezone::Lookup.config(:google) { |config| config.api_key = 'my_key' }
=> #<Timezone::Lookup::Google:0x0000555735f68b50
 @config=
  #<OpenStruct api_key="my_key", request_handler=Timezone::NetHTTPClient, protocol="https", url="maps.googleapis.com", uri=#<URI::HTTPS https://maps.googleapis.com>>>
pry: main > Timezone.lookup(43.4733376, -80.5325744)
=> #<Timezone::Zone name: "America/Toronto">
```

**Comment by XXChester** [comment]
Oh that would help, sorry. I'm using geonames

**Comment by XXChester** [comment]
Hmm I see with your example (and geonames) it returns properly....what the hell...

I'll have to keep digging. Thanks

**Comment by AlexWayfer** [comment]
I don't know. I can check with Geonames, but if you got the success — I'll not. You're welcome.

**Comment by XXChester** [comment]
Yeah don't waste your time. I must've changed a setting or something, I'll figure it out. Thanks for the quick reply.
