### ISSUE TITLE
Invalid Zone error on real coordinates lookup

### ISSUE THREAD

**Issue by eric-norcross** [panthomakos/timezone#105]
`Timezone::Error::InvalidZone (Timezone::Error::InvalidZone)` raised with `Timezone.lookup(1.9856557, -157.3504973)` which are  the coordinates for [Cassidy International Airport](https://www.google.com/maps/place/Cassidy+International+Airport/@1.9856557,-157.3504973,15z/data=!4m5!3m4!1s0x0:0x99ab09a901b62e75!8m2!3d1.9856557!4d-157.3504973)

Expected result: `Pacific/Kiritimati`

Using gem version 1.3.21

**Comment by panthomakos** [comment]
This might be an issue with the Google API. I tested these coordinates with Geonames and got the expected result.

```
irb(main):006:0> Timezone.lookup(1.9856557, -157.3504973)
=> #<Timezone::Zone name: "Pacific/Kiritimati">
```

Have you tried following up with the Google API folks? If you're able to introspect the response [here](https://github.com/panthomakos/timezone/blob/master/lib/timezone/lookup/google.rb#L38) I would be interested to see the API response you are getting.
