### ISSUE TITLE
Timezone::Error::NilZone: No zone was found. Please specify a zone.

### ISSUE THREAD

**Issue by c4ftabrez** [panthomakos/timezone#14]
I am trying to use this gem to get zone based on geocoding data. But I get the following error:

  Timezone::Error::NilZone: No zone was found. Please specify a zone.

I ran the following as per the documentation:
  timezone = Timezone::Zone.new :latlon => [-34.92771808058, 138.477041423321]

Has that functionality been discontinued?

**Comment by coderdave** [comment]
Probably would be good to add this stuff to the readme...

**Comment by panthomakos** [comment]
@coderdave the configuration instructions already explain that you need a geonames username: https://github.com/panthomakos/timezone#getting-the-timezone-for-a-specific-latitude-and-longitude

Did you have something else in mind?

**Comment by coderdave** [comment]
@panthomakos I didn't know I had to enable web services. But I found this issue and it helped.

**Comment by panthomakos** [comment]
@coderdave I added a note w/ a link to enable webservices for geonames. Hopefully this will help people in the same situation. Thanks for the clarification!
