### ISSUE TITLE
Alternative in case Geonames lookup fails

### ISSUE THREAD

**Issue by amnesia7** [panthomakos/timezone#15]
Hi,

I was wondering whether the option of using a local timezone database table had been considered as a fallback just in case Geonames lookups failed for whatever reason (eg the web service is down, too many requests in the time frame, etc).

There's a post here: http://stackoverflow.com/questions/5584602/determine-timezone-from-latitude-longitude-without-using-web-services-like-geona that mentions it.

There's a gist in a comment against the main answer that has all the cities and their lat,lngs: https://gist.github.com/1769458
The same comment also offers a suitable SQL select statement and the failover in case there isn't a suitable timezone city nearby.

What do you think?

**Comment by panthomakos** [comment]
Closing this ticket for the time being.  The idea is interesting, but there does not appear to be progress on it. I believe it would be very easy to write your own lookup/handler to do database lookups (as opposed to HTTP lookups) and if modifications need to be made to support that, I would be happy to take a look at a Pull Request for that.

In the gems current state I don't want to introduce a dependency on postresql or postgis.
