### ISSUE TITLE
Timezone::Error::NilZone: No zone was found. Please specify a zone.

### ISSUE THREAD

**Issue by rostaamm** [panthomakos/timezone#26]
Hi,
I enabled GeoNames free webservrices 5 hours ago and when I go to `http://www.geonames.org/enablefreewebservice` it says

     The account rostaamm has been successfully enabled to use the free webservices.

But when I run the following in my Rail4 application console

    timezone = Timezone::Zone.new :latlon => [-34.92771808058, 138.477041423321]

I get the error message:

     Timezone::Error::NilZone: No zone was found. Please specify a zone.

This is my first time using GeoNames so I'm not over the limit. How may I go about fixing this?
Thanks.

**Comment by panthomakos** [comment]
Closing this issue. If you can provide me with a stack trace or additional information I would be happy to re-open the issue. Thanks!
