### ISSUE TITLE
Error, uninitialized class variable @@username in Timezone::Configure

### ISSUE THREAD

**Issue by blklane** [panthomakos/timezone#31]
Error I am getting: `Timezone::Error::GeoNames: uninitialized class variable @@username in Timezone::Configure`

When I am trying to run:
`Timezone::Zone.new(latlon: [-122.4194155, 37.7749295])`

**Comment by panthomakos** [comment]
Did you configure the username? https://github.com/panthomakos/timezone#getting-the-timezone-for-a-specific-latitude-and-longitude

**Comment by blklane** [comment]
Ahh no, didn't see that.

**Comment by panthomakos** [comment]
FYI the upcoming release of this gem (0.3.10) will have a clearer configuration error message when this happens:

```
$ Timezone::Zone.new(latlon: [1,2])
Timezone::Error::InvalidConfig: missing username
```

**Comment by blklane** [comment]
Thanks @panthomakos!
