### ISSUE TITLE
Timezone for Arizona has wrong lookup

### ISSUE THREAD

**Issue by CorreyS** [panthomakos/timezone#32]
If a user ever has timezone 'America/Phoenix' and uses timezone.active_support_time_zone it will always return 'Mountain Time (US & Canada)', when in fact, Arizona should return 'Arizona' as it does not change timezones. ActiveSupport::TimeWithZone has a field just for Arizona as parts of the year it is Pacific Time, and other parts Mountain Time. The offset for Arizona is -0700 year round.

**Comment by panthomakos** [comment]
It appears the mapping is not correct in the `timezone` gem code.  Thanks for reporting this.

ActiveSupport only has "nice" names for 149 timezones, so I am only going to include those. The current mapping includes values for almost all timezones which is not accurate.

I will release a new patch version of this gem with only the `ActiveSupport::TimeZone` mappings included.

In a future release I will probably remove this method entirely as the mappings already exist in the `ActiveSupport::TimeZone` class.
