### ISSUE TITLE
Error executing a command from the README file

### ISSUE THREAD

**Issue by martinezcoder** [panthomakos/timezone#34]
In the README file, it says that I can get the Timezone with the latitud and longitud parameters.
```
timezone = Timezone::Zone.new :latlon => [-34.92771808058, 138.477041423321]
```

However, when I execute this code I get this error:
````
Timezone::Error::InvalidConfig: missing username
````

**Comment by panthomakos** [comment]
Please make sure you read the `README` instructions. They explains that you need to configure the gem w/ a username:

https://github.com/panthomakos/timezone#getting-the-timezone-for-a-specific-latitude-and-longitude

**Comment by martinezcoder** [comment]
:)
