### ISSUE TITLE
Timezone::Error::Google: 757: unexpected token at '�‹�'

### ISSUE THREAD

**Issue by goodmanship** [panthomakos/timezone#35]
I've been using this gem for months and it's been working great, but on Aug 20th, I started getting this error.  Any help appreciated!

backtrace:
vendor/bundle/ruby/2.2.0/gems/timezone-0.4.2/lib/timezone/lookup/google.rb:35 in rescue in lookup
vendor/bundle/ruby/2.2.0/gems/timezone-0.4.2/lib/timezone/lookup/google.rb:20 in lookup
vendor/bundle/ruby/2.2.0/gems/timezone-0.4.2/lib/timezone/zone.rb:225 in timezone_id
vendor/bundle/ruby/2.2.0/gems/timezone-0.4.2/lib/timezone/zone.rb:35 in initialize
app/controllers/sales/leads_controller.rb:175 in new
app/controllers/sales/leads_controller.rb:175 in timezone
...

leads_controller line 175:
zone = Timezone::Zone.new latlon: [params[:lat], params[:lng]]

**Comment by panthomakos** [comment]
Nothing changed on the timezone gem side, so my guess is that something changed with the google API or with your application. Can you provide me the actual call you are making (lat, lng)? Can you reproduce this in a Rails console? If so, can you provide me with the output of the following when run from the Rails console?

```
require 'timezone'

module Timezone
  module Lookup
    class Google < ::Timezone::Lookup::Basic
      def lookup(lat,lng)
        response = client.get(url(lat,lng))

        if response.code == '403'
          raise(Timezone::Error::Google, '403 Forbidden')
        end

        return unless response.code =~ /^2\d\d$/
        data = JSON.parse(response.body)

        puts data

        if data['status'] != 'OK'
          raise(Timezone::Error::Google, data['errorMessage'])
        end

        data['timeZoneId']
      rescue => e
        raise(Timezone::Error::Google, e.message)
      end
    end
  end
end

Timezone::Zone.new(latlon: [lat, lng])
```

**Comment by goodmanship** [comment]
You're right, it was not a timezone issue.  We upgraded to ruby 2.2.2 a few weeks ago which caused a problem with Net::HTTP response decoding due to a monkey patch from another gem.  
Thanks for looking at it

**Comment by panthomakos** [comment]
Hey, glad you sorted it out! Monkey patches can be tricky to debug. Monkey patching `Net::HTTP` sounds particularly nefarious.
