### ISSUE TITLE
Http wrapper not working

### ISSUE THREAD

**Issue by arturictus** [panthomakos/timezone#37]
When Creating a custom wrapper doesn't get the timezone

```ruby
Timezone::Zone.new(latlon: [48.11887, -1.527815]).zone
# => Timezone::Error::NilZone
```

### Outputting the response

```
puts response.body.to_s
{
   "dstOffset" : 0,
   "rawOffset" : 3600,
   "status" : "OK",
   "timeZoneId" : "Europe/Paris",
   "timeZoneName" : "Central European Standard Time"
}
```

```
puts response.code
200
```

### Code
```ruby
Timezone::Configure.begin do |c|
  c.google_api_key = 'blabla'
  c.http_client = ::TimezoneHTTPWrapper
end
````

```ruby
class TimezoneHTTPWrapper
  attr_reader :domain
  def initialize(protocol, host)
    @domain = URI.parse("#{protocol}://#{host}")
  end
  def get(path)
    url = _url(path)
    HTTP.get(url)
  end

  private

  def _url(str)
    URI.parse("#{domain}/#{str}").to_s
  end
end
```

I've tried to use a wrapper for the wrapper:
no luck

```ruby
class TimezoneHTTPWrapper
  attr_reader :domain
  def initialize(protocol, host)
    @domain = URI.parse("#{protocol}://#{host}")
  end

  def get(path)
    url = _url(path)
    Wrapp.new(HTTP.get(url))
  end

  private

  class Wrapp < Struct.new(:object)
    def body
      object.body.to_s
    end

    def code
      object.code
    end
  end

  def _url(str)
    URI.parse("#{domain}/#{str}").to_s
  end
end
```

**Comment by panthomakos** [comment]
I had to make a correction (changed `HTTP` to `::Net::HTTP`) to get the code to work, but I am still getting a different result than you are:

```
require 'timezone'
require 'net/http'

class TimezoneHTTPWrapper
  attr_reader :domain
  def initialize(protocol, host)
    @domain = URI.parse("#{protocol}://#{host}")
  end
  def get(path)
    url = _url(path)
    ::Net::HTTP.get(url)
  end

  private

  def _url(str)
    URI.parse("#{domain}/#{str}").to_s
  end
end

Timezone::Configure.begin do |c|
  c.username = '[FILTERED]'
  c.http_client = ::TimezoneHTTPWrapper
end

puts Timezone::Zone.new(latlon: [48.11887, -1.527815]).zone
```

Result:

```
.../lib/timezone/lookup/geonames.rb:30:in `rescue in lookup': undefined method `hostname' for #<String:0x00562531fce278> (Timezone::Error::GeoNames)
```

```
.../lib/timezone/lookup/google.rb:35:in `rescue in lookup': undefined method `hostname' for #<String:0x0055eaef06a128> (Timezone::Error::Google)
```

I can resolve that by changing the `_url` method to return the actual `URI` instead of a `String`:

```
  def _url(str)
    URI.parse("#{domain}/#{str}")
  end
```

But you still have a problem because `::Net::HTTP.get(url)` in your `get` method will still just return a string instead of an object that responds to `#body` and `#code`:

https://github.com/panthomakos/timezone#using-your-own-http-client

**Comment by arturictus** [comment]
Hi @panthomakos,
Thanks for the answer.
About the HTTP, I'm using a http gem because I was getting a Strong Error when doing multiple requests in sidekiq.
Here is the gem:
https://github.com/httprb/http

**Comment by panthomakos** [comment]
@arturictus I'm happy to help you debug issues related to `timezone` itself. I think in this case you need to address the errors that are occurring in your wrapper and URI handling first. If you can address those (see for example my code sample) then you should be able to use your wrapper (or the `HTTP::Response` object directly https://github.com/httprb/http/blob/master/lib/http/response.rb). As long as the response responds to `#body` and `#code` you should not need to make any additional changes.

**Comment by panthomakos** [comment]
Please re-open if you have an update!

**Comment by arturictus** [comment]
Hi @panthomakos, yes sorry, I did not had much time to investigate. I reopen when I have something to show.
Thank you.
