### ISSUE TITLE
Test lookup

### ISSUE THREAD

**Issue by icem** [panthomakos/timezone#39]
It would be nice to have ability to configure "test" lookup. Example from [geocoder](https://github.com/alexreisner/geocoder#testing-apps-that-use-geocoder) gem:
```
Geocoder.configure(:lookup => :test)
```

**Comment by panthomakos** [comment]
@icem here is what I'm thinking: https://github.com/panthomakos/timezone/pull/40

**Comment by icem** [comment]
@panthomakos that's great thank you. Looking forward to apply this on my project. Much better than hacking httpclient.
