### ISSUE TITLE
Timezone::Error::Google: This API project is not authorized to use this API

### ISSUE THREAD

**Issue by MaxPleaner** [panthomakos/timezone#41]
You say in the readme that this can be used with a "Google API key" but there are actually many different kinds of Google API keys. I created an API key for the Google geolocation service but got this error when trying to use the gem to find a time zone given latitude and longitude.

**Comment by MaxPleaner** [comment]
OK i figured this out. It is not the Google geolocation API I need to enable ... it is the Google maps Time Zone API. I suppose it's obvious although I didn't see the Time Zone option at first. I'll submit a pull request which adds a note in the README. Thank you for the work put in to this useful gem.

**Comment by panthomakos** [comment]
Thanks for the PR!
