### ISSUE TITLE
Troubles with frozen active support timezone mapping.

### ISSUE THREAD

**Issue by jaisonerick** [panthomakos/timezone#43]
The constant `TIMEZONE_MAPPING` on `Timezone::ActiveSupport` class has been frozen in the last version, but I was adding a few more mappings to it in order to match my custom rails mappings. The active support timezone class don't freeze this hash so we can add more specific timezones (like the others we have here, in Brazil). There's any way to "unfreeze" this hash?

Thanks!

**Comment by panthomakos** [comment]
@jaisonerick 

The plan is to remove this feature entirely in a near-future version of `timezone`.  The mapping is too tight of a coupling between this gem and Rails.  If `ActiveSupport::Timezone::MAPPING` ever changes I need to modify this gem and possibly create forwards/backwards incompatibilities unnecessarily.

Therefore, I am hesitant to expand/revert behavior at this point.  Might I suggest something a little different for you? If you create your own domain class to provide these mappings then you won't be dependent on my gem to provide the conversions. A good starting point might be:

```
module TimezoneToActiveSupport
  MAPPINGS = Hash[::ActiveSupport::Timezone::MAPPING.map{ |k,v| [v, k] }]
  # + whatever other mappings you want

  # Convert a timezone name to the active support equivalent. Fallback if a mapping
  # does not exist.
  def self.convert(timezone)
    MAPPINGS[timezone] || timezone
  end
end
```

Now you can simply replace calls to `timezone.active_support_time_zone` with `::TimezoneToActiveSupport.convert(timezone.zone)`.

This would allow you to couple your mappings with those that your version of `ActiveSupport` actually provides.

**Comment by panthomakos** [comment]
It also might be worth pointing out that `::ActiveSupport::TimeZone[timezone.zone]` will often give you what you are looking for.

**Comment by jaisonerick** [comment]
You're right. Now I see that this really doesn't seems to belong to this gem and it would be better removed in future versions. :+1: to that.

Thank you for the suggestion, it'll be very helpful.
