### ISSUE TITLE
 adds supports for beerpay! for get donations!

### ISSUE THREAD

**Issue by chebyte** [panthomakos/timezone#47]
Hi @panthomakos, I have been using this gem and I found it very usefull, please add this project to http://beerpay.io so I can donate you!

thanks for advance!

**Comment by panthomakos** [comment]
@chebyte I am glad you are finding this project useful.  I am not interested in receiving donations but please feel free to open issues if you find bugs or would like to suggest an improvement. Pull Requests are also always welcome!

Thanks!
