### ISSUE TITLE
SyntaxError: unexpected tLPAREN_ARG, expecting keyword_do_LAMBDA or tLAMBEG

### ISSUE THREAD

**Issue by kwokster10** [panthomakos/timezone#51]
Hi, 

I recently added your gem to my project (Rails 3.1.0 and Ruby 1.9.3). I got a syntax error right off the bat when I tried run the console after bundle install. 

It seemed similar to this issue:
https://github.com/rubinius/rubinius/issues/2595

So I opened the `timezone-0.99.1/lib/timezone/deprecate.rb` file and edited line 23 to get rid of the whitespace after lambda: 
```
@callback || ->(_, _, message) { warn(message) }
```
I saved and tried opening up the console again. Success!

I'm not sure if anyone else is running into this issue (I realize the Rails and Ruby versions in my project are very old now) but it seems like an easy inclusion for future versions.

Thanks!

**Comment by panthomakos** [comment]
This seems like a reasonable thing to fix even though `1.9.3` is not supported. I'll fix for the next patch release.
