### ISSUE TITLE
Upgrade Documentation

### ISSUE THREAD

**Issue by mikellevate** [panthomakos/timezone#53]
Please provide better upgrade documentation for 1.0 release.  While the config deprecation warning is obvious and noted in the README the method calls are not.  The incompatibility between new config/old method calls is especially disruptive.

**Comment by panthomakos** [comment]
Can you please clarify where you are having trouble w/ the upgrade or what methods are not working?  I am assuming [this](https://github.com/panthomakos/timezone/blob/master/README.markdown) is the README you are using for reference?

**Comment by mikellevate** [comment]
I've figured it all out now, but it would be good to document the full list of changes.  The particular problem I encountered was that changing the config forces you to use the new method calls -- but this is not documented anywhere.  You'll probably get users that change their config because of the deprecation warning but don't realize their method calls need to change as well.

**Comment by panthomakos** [comment]
Okay, I see. Thank you for the clarification! I'll update the documentation to indicate that the method calls need to be updated before the configuration is updated.
