### ISSUE TITLE
Example test case not working

### ISSUE THREAD

**Issue by stephenq** [panthomakos/timezone#54]
> Timezone.lookup(-34.92771808058, 138.477041423321)
Timezone::Error::InvalidZone: Timezone::Error::InvalidZone
	from ~/.rvm/gems/ruby-2.2.1/gems/timezone-0.99.2/lib/timezone.rb:50:in `fetch'
	from ~/.rvm/gems/ruby-2.2.1/gems/timezone-0.99.2/lib/timezone.rb:75:in `lookup'

**Comment by panthomakos** [comment]
@stephenq I am able to get this working with geonames. It is possible that the lookup does not return anything for google. If that is the case I am happy to update the documentation. Can you confirm if the following returns a proper value with your configuration:

```
Timezone.lookup(-34.98058, 138.477041)
```

**Comment by ArnaudRemi** [comment]
```
Timezone.lookup(48.8793945, 2.3690545)
Timezone::Error::InvalidZone: Timezone::Error::InvalidZone
```

This is also returning error, lookup is configured with geonames.

**Comment by panthomakos** [comment]
That code also works for me.

```
Timezone.lookup(48.8793945, 2.3690545)
=> #<Timezone::Zone name: "Europe/Paris">
```

Can you tell me what the following outputs for you?

```
Timezone.lookup(48.8793945, 2.3690545){ |name| puts "*#{name}*" }
```

Are you using a custom http handler?

**Comment by aliceclv** [comment]
```
Timezone.lookup(48.8793945, 2.3690545){ |name| puts "*#{name}*" }
**
 => nil
```
Thanks for your quick answer :) Same issue/project than @ArnaudRemi.
It's working locally but not on our server. We're not using a custom http handler.

**Comment by panthomakos** [comment]
This is very strange. Could you run the following in your console? My guess is that the geonames API is not returning a 200 response for some reason. (remember to filter your username in the URL)

```
Timezone::Lookup.lookup.client
=> #<Timezone::NetHTTPClient:0x00561fe7ce8238 @http=#<Net::HTTP api.geonames.org:80 open=false>>

url = Timezone::Lookup.lookup.send(:url, 48.8793945, 2.3690545)
=> "/timezoneJSON?lat=48.8793945&lng=2.3690545&username=[FILTERED]"

resp = Timezone::Lookup.lookup.client.get(url)
=> #<Net::HTTPOK 200 OK readbody=true>

resp.body
=> "{\"sunrise\":\"2016-05-03 06:25\",\"lng\":2.3690545,\"countryCode\":\"FR\",\"gmtOffset\":1,\"rawOffset\":1,\"sunset\":\"2016-05-03 21:09\",\"timezoneId\":\"Europe/Paris\",\"dstOffset\":2,\"countryName\":\"France\",\"time\":\"2016-05-03 19:09\",\"lat\":48.8793945}"
```

**Comment by aliceclv** [comment]
I ran your code and you were right, it is indeed coming from Geonames. I had the following answer:

```
"{\"status\":{\"message\":\"user account not enabled to use the free webservice. Please enable it on your account page: http://www.geonames.org/manageaccount \",\"value\":10}}
```
So I now enabled it :)
I also realized my geonames username was different from the server one (I was testing it before and then I created a project username), the reason why it was working locally.
Sorry for the bother and thank you for you answers.

**Comment by panthomakos** [comment]
Okay, thank you for the response! I will create a ticket to provide a better error message in this case.

**Comment by panthomakos** [comment]
@aliceclv for the failure you posted, can you also provide the HTTP status code?

```
resp = Timezone::Lookup.lookup.client.get(url)
=> #<Net::HTTPOK 200 OK readbody=true>
```

**Comment by aliceclv** [comment]
@panthomakos It returned a 200 OK, just like the one you've pasted in your message.

**Comment by panthomakos** [comment]
@aliceclv thank you! I have improved exceptions in the `master` branch, so that when they do occur you will receive a more meaningful message.
