### ISSUE TITLE
hash will be deprecated in the next release

### ISSUE THREAD

**Issue by ijunaidfarooq** [panthomakos/timezone#56]
`Creating Zone objects using an options hash will be deprecated in the next release of the `timezone` gem. Use `Timezone::[]`, `Timezone::fetch` or `Timezone::lookup` instead.`

is this will be shown on any violation or by default just to remind that if you have been using hash then remove it?

As i have cleaned my code but this caution never goes...??

**Comment by panthomakos** [comment]
@ijunaidfarooq this means you are probably using code such as `Timezone::Zone.new(...)`. Instead you should be using [`Timezone::[]`](http://www.rubydoc.info/gems/timezone/0.99.2/Timezone#%5B%5D-class_method) ,[`Timezone::fetch`](http://www.rubydoc.info/gems/timezone/0.99.2/Timezone#fetch-class_method) or [`Timezone::lookup`](http://www.rubydoc.info/gems/timezone/0.99.2/Timezone#lookup-class_method).

For instance, instead of using `Timezone::Zone.new(lat: 5, lon: 5)` you would use `Timezone.lookup(5, 5)`.

If you can give an example of the code that is causing this issue I can assist you further.

**Comment by ijunaidfarooq** [comment]
this is all my codings
its specific branch with some update coding https://github.com/evercam/evercam-api/tree/update_time_zonegem_and_codings

and this is my whole codebase https://github.com/evercam/evercam-api But yet failed to found out about the above Deprecation. It was giving me 2 deprecations one is removed in above branch but 2nd one is not even finding in the code.

**Comment by panthomakos** [comment]
I see a few uses that need to be corrected:

`Timezone::Zone.names` should be `Timezone.names`

https://github.com/evercam/evercam-api/blob/update_time_zonegem_and_codings/lib/actors/camera_create.rb#L58
https://github.com/evercam/evercam-api/blob/update_time_zonegem_and_codings/lib/actors/camera_update.rb#L65

Although these would be much more efficient as:

```
unless Timezone[timezone].valid?
  add_error(...)
end
```

I could not find uses of `Timezone::Zone` in your branch (please confirm you are still getting that same deprecation warning in the branch you linked). But I did find some incorrect usages of `lookup`:

https://github.com/evercam/evercam-api/blob/update_time_zonegem_and_codings/spec/actors/camera_create_spec.rb#L190
https://github.com/evercam/evercam-api/blob/update_time_zonegem_and_codings/spec/actors/camera_update_spec.rb#L150

I think what you intended was:

```
        it 'sets the timezone value when provided' do
          timezone = Timezone['America/Chicago']
          params = valid.merge(timezone: timezone.name)

          outcome = subject.run(params)
          result = outcome.result

          expect(outcome).to be_success
          expect(result.timezone).to eq(timezone)
        end
```

Although I don't see why the `Timezone` part is even necessary, you could just use:

```
params = valid.merge(timezone: 'America/Chicago')
```

**Comment by panthomakos** [comment]
Please re-open if this is still relevant or if you have additional questions.
