### ISSUE TITLE
Can't precompile in Rails without lookup api key set

### ISSUE THREAD

**Issue by filipegiusti** [panthomakos/timezone#58]
I want to:

- Add configuration for google lookup in initializer setting api key with an env var.

```ruby
Timezone::Lookup.config(:google) do |c|
  c.api_key = ENV["GOOGLE_MAPS_API_KEY"]
end
```

- Run `RAILS_ENV=production bundle exec rails assets:precompile` in my local machine without GOOGLE_MAPS_API_KEY env var set.

This raises `Timezone::Error::InvalidConfig: missing api key` but I don't need an instance of Lookup for precompilation.

The initializer shouldn't instantiate a new Lookup, it should only store the configuration and when `Timezone.lookup` is used it should lazily instantiate a lookup.

**Comment by panthomakos** [comment]
The lookup is instantiated immediately for a few reasons. The main reason is that validation happens immediately, so invalid configurations don't raise an error on first use - which could happen at any time during execution and cause the program to fail. There are secondary reasons related to optimizing the call for forking servers (and only instantiating a single lookup class).

There are a few things I would recommend if you want to lazily configure or if you want to skip configuration entirely.

The first is to skip configuration if you don't have a key. This is simple to accomplish and ensures that you only configure a lookup if you have a valid lookup configuration.

```
if ENV['GOOGLE_MAPS_API_KEY']
  Timezone::Lookup.config(:google) { |c| c.api_key = ENV['GOOGLE_MAPS_API_KEY'] }
end
```

The second is to lazily configure the lookup when you use it by wrapping the configuration in a module/ gem wrapper of your own. This allows you to accomplish lazy instantiation without depending on the gem's internal implementation.

```
module TimezoneLookup
  class << self
    def lookup(*args)
      config
      Timezone.lookup(*args)
    end
    
    private
    
    def config
      @lookup ||= Timezone::Lookup.config(:google){ ... }
    end
  end
end
```

**Comment by filipegiusti** [comment]
Yeah, I already went with something like the second approach, but I was surprised by the implementation. Raising an exception when you only want to add configuration values is surprising. I understand the reasoning but disagree, so I would expect at minimum to have an alternative that would mean only setting an attribute to true or calling a different method.

I propose something like

```ruby
Timezone::Lookup.config(:google, lazily_instantiate: true) do |c|
  c.api_key = ENV["GOOGLE_MAPS_API_KEY"]
end
```

and it would only `warn "InvalidConfig: missing api key"` on configuration-time.

**Comment by panthomakos** [comment]
You also do have the option of passing a dummy value in. For instance:

```
Timezone::Lookup.config(:google) { |c| c.api_key = ENV['GOOGLE_MAPS_API_KEY'] || 'stub' }
```

I don't think this is unprecedented. For example, Rails itself will raise an exception when passed a value it does not expect. For instance, you can't pass a `nil` or a `Fixnum` to `config.autoload_paths <<` - while a `String` is allowed even if the path does not exist.

I would prefer, in this case, to keep the API smaller and the behavior consistent.  Even if it means some additional work on the consumer's part when they want to forgo configuration.

**Comment by filipegiusti** [comment]
OK, feel free to close the issue.
Em 5 de mai de 2016 19:26, "Pan Thomakos" <notifications@github.com>
escreveu:
