### ISSUE TITLE
Slow geonames api

### ISSUE THREAD

**Issue by ssurfr2819** [panthomakos/timezone#59]
Since the last two days, we receive many timeout exceptions (greater than 10 seconds) on calls that are generated by the timezone gem to api.geonames. During the past two years, we don't think we received any such exceptions. I've looked at the geonames website for potential indication that they are experiencing issues, but could not find any current announcements. Is it possible that the timezone gem is causing this?

The exception occurs when converting lat/lng to timezone with geonames configured.

We are attempting to rescue such exceptions, but unfortunately they are not caught by the Timezone call itself, and instead get trapped by our request timeout gem. (Have tried settings as long as 15 seconds!)

**Comment by panthomakos** [comment]
There have been no changes to the request structure or API on the `timezone` gem side - certainly none in the last two days.

Locally some simple benchmarks give me an average request+response time of 2.5 seconds. While that's slow for a webservice, it's certainly nothing in the range of 15+ seconds.

Are you using a custom HTTP wrapper? Have you investigated if you are being rate limited by the geonames API? It's possible that you need to upgrade if you are hitting your rate limit.

**Comment by ssurfr2819** [comment]
We are a very low use app, still in beta. Heroku suggested it could be due to IP limiting, and wants us to use a (paid) add-on to act as work around for dedicated IPs. But I understand geonames uses our username for limits, so that doesn’t make sense. 

 

No, we aren’t using a custom wrapper, just timezone gem doing its thing.

**Comment by ssurfr2819** [comment]
I doubt this issue is caused by the timezone gem, but its very odd what we observe. Using the rails console, with timezone configured with Timezone::Lookup.configure(:geonames)... (setting our username), we observed a request for a lookup to return "execution error", and a following identical request to operate successfully:
```
irb(main):018:0> z=Timezone.lookup(t.latitude,t.longitude)
Timezone::Error::GeoNames: execution expired
	from /Users/Shawn/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/timezone-0.99.2/lib/timezone/lookup/geonames.rb:34:in `rescue in lookup'
	from /Users/Shawn/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/timezone-0.99.2/lib/timezone/lookup/geonames.rb:22:in `lookup'
	from /Users/Shawn/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/timezone-0.99.2/lib/timezone.rb:75:in `lookup'
	from (irb):18
	from /Users/Shawn/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/railties-3.2.22.1/lib/rails/commands/console.rb:47:in `start'
	from /Users/Shawn/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/railties-3.2.22.1/lib/rails/commands/console.rb:8:in `start'
	from /Users/Shawn/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/railties-3.2.22.1/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
irb(main):019:0> z=Timezone.lookup(t.latitude,t.longitude)
=> #<Timezone::Zone name: "Pacific/Honolulu">
irb(main):020:0> 
```
Note the variable "t" is set to an object that includes latitude and longitude attributes. The current attribute values were located in the Hawaiian islands.

So, in the IRB console, we observed similar to what we are experiencing in the code.

Then reconfigured the Timeout gem to use google api, restarted the console and issued the same commands to see quick responses with no errors. 

This problem could very well be our own code (somehow?) or configuration (currently Ruby 2.0.0 and Rails 3.2.22) but I think it is unlikely. It is not rate limits, that I can tell. Perhaps something makes sense to you from the error trace in the above responses. Even if it is due to our system/configuration/code, it might be worth others knowing about.

In the meantime, we are probably going to switch to Google engine...

**Comment by panthomakos** [comment]
That error is raised by the Ruby `NetHTTP` library and then wrapped in a common exception - it indicates that either the read or open timeouts were exceeded. I am assuming you have configured the timeouts with higher limits for your tests like this?

```
Timezone::Lookup.config(:geonames) do |c|
  c.open_timeout = 10
  c.read_timeout = 10
end
```

Unfortunately there is not much more information that I can provide you, because `timezone` never received a response from Geonames in this case. In `master` (and in `v1.0.0`) if there is an error coming back from Geonames, it will be displayed as the exception message (see https://github.com/panthomakos/timezone/commit/45c4e0e789cff02078a5584dbd28a8038aa651f5). Maybe this will be of help to you going forward.

I am not sure that I understand your question:

> Do you understand why the timezone gem isn't catching and raising the exception? From your code, I see it defaults http client to 5 seconds, whereas we set our request timeout gem to 10 or 15 for these tests. Shouldn't your code be catching the event, and reporting to us?

From your example it looks as though the `timezone` gem is raising the exception. Can you clarify?

P.S: I have certainly run into issues w/ limits on Geonames. Although I don't know if they limit based on IP address. In my case I upgraded to a paid plan (with Geonames) and have not had issues since then.

**Comment by ssurfr2819** [comment]
First, its great that you respond to people trying to use your invention. :)

This is definitely not a case of limits based on IP. The last runs within IRB were made on my local machine, so the IPs are not going to be the same as the production app on Heroku. 

I had seen in your source that you had configured HTTP client to include an open or read timeout that included " ... || 5" so I inferred that the timeouts would default to 5 seconds. I had not configured them otherwise. But I have the Request Timeout gem guarding things and my last runs were with a configuration of 8 seconds. That's the same time I inserted Begin/Rescue around the Timezone calls to convert lat/lng. So if your code defaults to 10 seconds rather than the 5 seconds, perhaps I was misled to think your exception trapping wasn't working. Also, just so you know, until now we've been using 0.6.0 Timezone. We upgraded to 0.99.x when we observed these issues. That's also when we tried the console experiment, and proved even then that geonames is basically not even responding. (Yet another request will respond successfully!)

I'm sure this is confusing. What I can say is that geonames is acting unusually. After a couple years of operation without issues, its throwing errors frequently (maybe like 1 in 5 times?). We've switched to google for now, and I'm not sure we'll look back. The upside is that we've migrated to your newer codebase.

Mahalo!

**Comment by panthomakos** [comment]
@ssurfr2819 Thanks for getting back to me.  I admit I am a little confused with the version switches thrown in there, but it doesn't matter much at this point.

I'm glad Google and the new gem version are working for you!

Best of luck!

**Comment by flyflytn** [comment]
Hi, I had the same issues with the Google API so just thought I'd put this here in case others are looking.

It would raise an exception for the very first lookup, and subsequent lookups would all work fine. A bit of wiresharking showed that the initial TLS connection setup with google was slow and seemed to be interrupted and retrying. After reading your post about raising the open and read timeouts, I tried that and that stopped the exceptions. So just appears that the time for TLS negotiation was too slow for the default timeouts.
thanks for the gem too.
