### ISSUE TITLE
Expose timezone abbreviation [enhancement]

### ISSUE THREAD

**Issue by craibuc** [panthomakos/timezone#64]
I noticed that many of the data files (e.g. https://github.com/panthomakos/timezone/blob/master/data/America/Chicago) include the timezone's abbreviation.

Would you consider adding a method to the `Timezone` class to provide the abbreviations and the one that is appropriate for the `time_with_offset` method?

**Comment by panthomakos** [comment]
If you have any interest in implementing this, please feel free to do so!  If not, I will try to take a crack at it in the next couple weeks.
