### ISSUE TITLE
InvalidZone error

### ISSUE THREAD

**Issue by aashish** [panthomakos/timezone#65]
Hi,
I am getting error as InvalidZone with following code

```
res = Geokit::Geocoders::GoogleGeocoder.geocode('140 Market St, San Francisco, CA')
timezone = Timezone::Zone.new(:lat => res.lat, :lon => res.lng)  
p timezone 
 => #<Timezone::Zone name: "{:lat=>17.4088912, :lon=>78.51124089999999}"> 

p  timezone.time Time.now  
```
 error as 
`Timezone::Error::InvalidZone: Timezone::Error::InvalidZone`

Thanks
Aashish

**Comment by panthomakos** [comment]
Can you please provide the version of `timezone` you are using? Also, have you configured Geonames or Google as the timezone lookup? Using the latest version of `timezone` and configuring w/ Geonames, I have this result:

```
> Timezone.lookup(17.4088912, 78.51124089999999)
=> #<Timezone::Zone name: "Asia/Kolkata">
```

**Comment by aashish** [comment]
It got fixed with 
`Timezone.lookup(17.4088912, 78.51124089999999)`
