### ISSUE TITLE
Timezone::Configure does not work

### ISSUE THREAD

**Issue by KMarshland** [panthomakos/timezone#66]
I'm attempting to configure the google api key using the code in the readme: 
```
Timezone::Configure.begin do |c|
      c.google_api_key = ENV['GOOGLE_PUBLIC']
end
``` 
in application.rb

However, when I do so, I get `NameError: uninitialized constant Timezone::Configure`.

**Comment by panthomakos** [comment]
Which version of the gem are you using? Ever since `0.99.*` you should be configuring Google using `::Timezone::Lookup.config(:google)`: https://github.com/panthomakos/timezone#lookup-configuration-with-google

**Comment by KMarshland** [comment]
That solves it. It seems I was linked to https://github.com/panthomakos/timezone/tree/34c94ea5679bc6fdaf3ba464bce0a3ef2d76e42e from a StackOverflow post, which was out of date. Hopefully this will help anyone coming from the same place.
