### ISSUE TITLE
Some Zip codes don't work

### ISSUE THREAD

**Issue by grandmasterspoc** [panthomakos/timezone#67]
the zip code `66202` returns nil. 

I'm not sure about other zip codes because my loop broke before it got any further

Please fix?

Thanks!

**Comment by panthomakos** [comment]
Please provide more details.  I am unaware of any zip-codes that are handled by this gem.  What version of this gem are you using? Can you provide a code sample?

**Comment by panthomakos** [comment]
Please re-open when you have additional information.
