### ISSUE TITLE
Net/HTTP error

### ISSUE THREAD

**Issue by djkazic** [panthomakos/timezone#68]
After initialization, the .lookup using GeoNames will cause an 'undefined method 'closed?'' error to be thrown. This is not reproducible in the interactive console, but has been observed in deployment.

Running on Ruby 2.3.1 with newest libraries.

**Comment by panthomakos** [comment]
Can you please provide me with a more complete backtrace and error message?

Additionally, what type of stack (or part of the stack) are you running in deployment when this is observed? Example: Rails, Sinatra, Puma, Webrick, Passenger + NGINX, Sidekiq Worker, Resque Worker...

**Comment by panthomakos** [comment]
Please re-open when you can provide additional details.
