### ISSUE TITLE
Issue w/ too many open files

### ISSUE THREAD

**Issue by hamza** [panthomakos/timezone#91]
I'm using this gem in my application, and last night encountered an issue w/ elevated error rate on my servers. The errors were `Errno::EMFILE - Too many open files`, and upon looking at individual web server processes, found that certain of them had anomalous levels of open files.

The files themselves had the following pattern —

```
# truncated …
<path>/20180524231947/bundled_gems/ruby/2.2.0/gems/timezone-0.1.5/data/America/Los_Angeles.json
<path>/20180524231947/bundled_gems/ruby/2.2.0/gems/timezone-0.1.5/data/America/Los_Angeles.json
<path>/20180524231947/bundled_gems/ruby/2.2.0/gems/timezone-0.1.5/data/America/Los_Angeles.json
<path>/20180524231947/bundled_gems/ruby/2.2.0/gems/timezone-0.1.5/data/America/Los_Angeles.json
<path>/20180524231947/bundled_gems/ruby/2.2.0/gems/timezone-0.1.5/data/America/Los_Angeles.json
<path>/20180524231947/bundled_gems/ruby/2.2.0/gems/timezone-0.1.5/data/America/Los_Angeles.json
<path>/20180524231947/bundled_gems/ruby/2.2.0/gems/timezone-0.1.5/data/America/Los_Angeles.json
<path>/20180524231947/bundled_gems/ruby/2.2.0/gems/timezone-0.1.5/data/America/Los_Angeles.json
<path>/20180524231947/bundled_gems/ruby/2.2.0/gems/timezone-0.1.5/data/America/Los_Angeles.json
<path>/20180524231947/bundled_gems/ruby/2.2.0/gems/timezone-0.1.5/data/America/Los_Angeles.json
<path>/20180524231947/bundled_gems/ruby/2.2.0/gems/timezone-0.1.5/data/America/Los_Angeles.json
```

So, redundant instances of these timezone datafiles held open by the web servers.

Restarting the offending processes resolved the acute issue, but at least twice since the incident I've seen the number of open files creep up again for some processes.

We have not updated the version of this Gem for some time, but this just randomly started occurring.

Has anyone else encountered a similar issue? Any insight into what could be causing it? Thanks!

**Comment by panthomakos** [comment]
For the version you are using, I suspect this is likely a bug with this line:

https://github.com/panthomakos/timezone/blob/0.1.1/lib/timezone/zone.rb#L36

But you are using a very old version of the gem. Upgrading to 0.99 (which is backwards compatible) will resolve this issue and allow a nice migration path to v1 going forward.

**Comment by hamza** [comment]
We have updated as you suggested and the problem seems to have abated. Thanks!

**Comment by panthomakos** [comment]
Woot! Glad that resolved the issue for you.
